# Generated by Django 3.2.12 on 2022-04-18 00:02

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pseudo', models.CharField(blank=True, max_length=48, unique=True, verbose_name="non d'utilisateur")),
                ('bio', models.CharField(blank=True, max_length=250, verbose_name='titre du profil')),
                ('img_profile', cloudinary.models.CloudinaryField(blank=True, default='https://res.cloudinary.com/dm68aag3e/image/upload/v1649743168/default-img-profile_hrhx6z.jpg', max_length=255, null=True, verbose_name='photo de profile')),
                ('img_bg', cloudinary.models.CloudinaryField(blank=True, default='https://res.cloudinary.com/dm68aag3e/image/upload/v1649743327/default-img-bg_zbeoo4.jpg', max_length=255, null=True, verbose_name='photo de couverture')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='date de naissence')),
                ('gender', models.CharField(blank=True, choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1, verbose_name='sexe')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='téléphone')),
                ('adress', models.CharField(blank=True, max_length=128, verbose_name='adresse')),
                ('town', models.CharField(blank=True, max_length=68, verbose_name='ville')),
                ('region', models.CharField(blank=True, max_length=68, verbose_name='région')),
                ('zipcode', models.CharField(blank=True, max_length=22, verbose_name='code postal')),
                ('country', models.CharField(blank=True, max_length=45, verbose_name='pays')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('link_linkedin', models.URLField(blank=True, verbose_name='lien de votre profile linkedin')),
                ('link_gitthub', models.URLField(blank=True, verbose_name='lien de votre profile gitthub')),
                ('link_twitter', models.URLField(blank=True, verbose_name='lien de votre twitter')),
                ('link_mysite', models.URLField(blank=True, verbose_name='lien de votre de site web')),
                ('number_views', models.IntegerField(blank=True, default=0, null=True, verbose_name='Nombre de vue profil')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='date de modification')),
                ('friends', models.ManyToManyField(blank=True, related_name='friends', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
            },
        ),
    ]
