# Generated by Django 4.2 on 2023-05-01 19:37

import apps.utils.function
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(blank=True, max_length=500, verbose_name='code identifiant')),
                ('pseudo', models.CharField(blank=True, max_length=48, unique=True, verbose_name="non d'utilisateur")),
                ('bio', models.CharField(blank=True, max_length=250, verbose_name='titre du profil')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='date de naissence')),
                ('img_profile', models.ImageField(blank=True, default='mediafiles/default/profile_jyytyz.jpg', null=True, upload_to=apps.utils.function.rename_profile_img, verbose_name='photo de profile')),
                ('img_bg', models.ImageField(blank=True, default='mediafiles/default/bg_r0siq1.jpg', null=True, upload_to=apps.utils.function.rename_profile_img, verbose_name='photo de couverture')),
                ('img_profile_str', models.CharField(blank=True, default='https://res.cloudinary.com/dm68aag3e/image/upload/v1649743168/default-img-profile_hrhx6z.jpg', max_length=500, null=True)),
                ('img_bg_str', models.CharField(blank=True, default='https://res.cloudinary.com/dm68aag3e/image/upload/v1649743327/default-img-bg_zbeoo4.jpg', max_length=500, null=True)),
                ('is_fixture', models.BooleanField(default=False)),
                ('is_updating_img_profile', models.BooleanField(default=False, verbose_name='is updating img profile')),
                ('is_updating_img_bg', models.BooleanField(default=False, verbose_name='is updating img bg')),
                ('gender', models.CharField(blank=True, choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1, verbose_name='sexe')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='téléphone')),
                ('adress', models.CharField(blank=True, max_length=128, verbose_name='adresse')),
                ('town', models.CharField(blank=True, max_length=68, verbose_name='ville')),
                ('region', models.CharField(blank=True, max_length=68, verbose_name='région')),
                ('zipcode', models.CharField(blank=True, max_length=22, verbose_name='code postal')),
                ('country', models.CharField(blank=True, max_length=45, verbose_name='pays')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('link_linkedin', models.URLField(blank=True, verbose_name='lien de votre profil linkedin')),
                ('link_gitthub', models.URLField(blank=True, verbose_name='lien de votre gitthub')),
                ('link_twitter', models.URLField(blank=True, verbose_name='lien de votre twitter')),
                ('link_mysite', models.URLField(blank=True, verbose_name='lien de votre site web')),
                ('number_views', models.IntegerField(blank=True, default=0, null=True, verbose_name='Nombre de vue profil')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='date de modification')),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
            },
        ),
    ]
