# Generated by Django 4.2 on 2023-05-06 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['-date_updated'], 'verbose_name': 'Profile', 'verbose_name_plural': 'Profiles'},
        ),
    ]
