# Generated by Django 3.2.12 on 2022-05-22 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_remove_profile_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='uid',
            field=models.CharField(blank=True, max_length=500, verbose_name='code identifiant'),
        ),
    ]
