# Generated by Django 3.2.12 on 2022-06-05 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_profile_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_updating_img_bg',
            field=models.BooleanField(default=False, verbose_name='is updating img bg'),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_updating_img_profile',
            field=models.BooleanField(default=False, verbose_name='is updating img profile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='link_gitthub',
            field=models.URLField(blank=True, verbose_name='lien de votre gitthub'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='link_linkedin',
            field=models.URLField(blank=True, verbose_name='lien de votre profil linkedin'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='link_mysite',
            field=models.URLField(blank=True, verbose_name='lien de votre site web'),
        ),
    ]
