# Generated by Django 4.2 on 2023-05-01 19:37

import apps.utils.function
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LikePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(choices=[('Like', 'Like'), ('Unlike', 'Unlike')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(blank=True, max_length=500, verbose_name='code post')),
                ('message', models.TextField(blank=True, verbose_name='message')),
                ('img', models.ImageField(blank=True, null=True, upload_to=apps.utils.function.rename_post_img_video, validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'gif'])], verbose_name='image')),
                ('img_str', models.CharField(blank=True, max_length=500, null=True)),
                ('is_fixture', models.BooleanField(default=False)),
                ('video', models.FileField(blank=True, null=True, upload_to=apps.utils.function.rename_post_img_video, verbose_name='video')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='date updated')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
                'ordering': ('-date_created',),
            },
        ),
    ]
