# Generated by Django 3.2.12 on 2022-05-01 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='uid',
            field=models.CharField(blank=True, max_length=64, verbose_name='code post'),
        ),
    ]
