# Generated by Django 3.2.12 on 2022-06-10 19:50

import apps.utils.function
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_alter_post_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to=apps.utils.function.rename_post_img_video, verbose_name='video'),
        ),
    ]
