# Generated by Django 3.2.12 on 2022-05-22 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_uid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='uid',
        ),
    ]
