# Generated by Django 3.2.12 on 2022-07-02 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_customuser_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(help_text='Required to authenticate', max_length=255, unique=True, verbose_name='email address'),
        ),
    ]
