# Generated by Django 4.2 on 2023-04-27 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_notif', models.CharField(choices=[('Like_Post', 'Like Post'), ('Add_Post', 'Add Post'), ('Add_Comment', 'Add Comment'), ('invitation_accepted', 'invitation accepted'), ('invitation_send', 'invitation send'), ('seen_profile', 'seen profile')], max_length=30, verbose_name='type_notif')),
                ('seen', models.BooleanField(default=False)),
                ('bg_seen', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('comment_post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notif_comment_post', to='comments.comment')),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
    ]
